const data = {
    bonusIcon                   : 'help_outline',                                                                                                            
    myProfile                   : 'person_outlineMy Profile',
    settings                    : 'settingsSettings',
    profileLogout               : 'logoutLogout',
    tabGeneral                  : 'General',
    tabDetails                  : 'Details',
    tabSecurity                 : 'Security',
    tabFollowings               : 'My Followings',
    tabInvoices                 : 'Invoices',
    tabPackages                 : 'Packages',
    deleteConfirm               : 'Delete Photo',
    profilePhotoPath            : 'cypress/fixtures/',
    profilePhotoDelete          : 'Are you sure you want to delete your photo?',
    imageFormat                 : 'The file must be a file of type: jpeg, png, jpg, gif.',
    nameAlert                   : 'Please Note!After your profile is approved you will not be able to change your name, surname during 60 days period.',
    countryAlert                : 'The Country field is required.',
    provinceAlert               : 'The Province field is required.',
    playerCountry               : 'United States',
    playerCity                  : 'São Paulo',
    playerAddress               : 'Rua Amauri, 513, Itaim Bibi District, São Paulo, CEP 01448-000, Brazi',
    playerPhone                 : '123456789',
    playerSchool                : 'The British College of Brazil',
    playerUni                   : 'Chácara Flora Campus',
    playerAgent                 : 'JORGE GARCIA SPORTS',
    marktLink                   : 'https://www.transfermarkt.com/neymar/profil/spieler/68290',
    
    minHeight                   : '29',
    maxHeight                   : '241',
    normalHeight                : '180',
    heightAlertMin              : 'The Height must be at least 80.',
    heightAlertMax              : 'The Height must not be greater than 210.',
    weightAlertMin              : 'The Weight must be at least 20.',
    minWeight                   : '19',
    maxWeight                   : '141',
    normalWeight                : '80',
    weightAlertMax              : 'The Weight must not be greater than 140.',
    nationalityAlert            : 'The Nationality field is required.',
    genderAlert                 : 'The Gender field is required.',
    descriptionTxt              : 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Sed do eiusmod tempor.',
    nationality                 : 'American',
    gender                      : 'Male',
    year                        : '2000',
    day                         : '21',    
    firstPosition               : 'Central defensive midfielder',
    secondPosition              : 'Right back',
    preferFoot                  : 'Left Footed',
    positionLabel               : 'Preferred Position &amp; Foot',
    positionFirst               : 'Preferred position',
    positionAlert               : 'The Preferred position field is required.',
    positionSecond              : 'Secondary position (Optional)',
    footAlert                   : 'The Preferred foot field is required.',
    prefFoot                    : 'Preferred foot',
    passwordAlert               : 'The current password field is required.',
    rePasswordAlert             : 'The Password field is required',
    invalidCred                 : 'Invalid email or password.',
}

export default data;

