const clubData = {
    imgUploadPath           : 'cypress/fixtures/img3.jpeg',
    clubsTabAll             : 'appsAll Clubs',
    clubsTabMy              : 'done_outlineMy Clubs',
    clubsTabFollow          : 'how_to_regFollowing',
    logoErrMsg              : 'The Logo field is required.',
    nameErrMsg              : 'The Club name field is required.',
    emailErrMsg             : 'The Email field is required.',
    descriptionErrMsg       : 'The Description field is required.',
    urlErrMsg               : 'The Website must be a valid URL.',
    clubEmail               : 'club1@gmail.com',
    clubWebSite             : 'club1@gmail.com',
    clubCountry             : 'United States',
    clubCountryCode         : '+1',
    clubPhone               : '123456789',
    socialPhone             : 'tel:(+1) 123456789',
    socialEmail             : 'mailTo:club1@gmail.com',
    socialUrl               : 'https://www.club1.com',
    moderationWaiting       : 'Your club will be published after moderation',
    clubEdit                : 'Edit page',
    clubDelete              : 'deleteDelete',
    clubDescription         : 'Description',
    clubDescrText           : 'Lorem ipsum dolor',
    playerAddText           : 'To add staff please start typing and select from our suggestions.',
    playerName              : 'Amanda',
    playerNameLong          : 'Amanda DiazPendingclose',
    coachName               : 'Coach',
    adminName               : 'c1 c1',
    adminRole               : 'Page owner',
    coachNameLong           : 'Coach CoachPendingclose',
    adminTitle              : 'Page adminsAdd',
}

export default clubData;